use strum::EnumIter;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumIter)]
pub enum Lingo {
    AddFriend,
    AttemptingReconnect,
    Cancel,
    Categories,
    Connected,
    ConnectionEstablished,
    ConnectionLost,
    CopiedToClipboard,
    Disconnected,
    FetchingUserInfo,
    FriendRequestDeclined,
    FriendRequestReceived,
    FriendRequestSent,
    FriendRemoved,
    Friends,
    FriendsSince,
    FriendAdded,
    FriendCode,
    General,
    Latency,
    List,
    Logout,
    ModalRemoveFriendTitle,
    ModalRemoveFriendBody,
    NoFriends,
    NoFriendRequests,
    Pending,
    Remove,
    Requests,
    Sandbox,
    ServerTime,
    Settings,
    UiScale,
    XAgo,
}
