//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::friendship::Entity as Friendship;
pub use super::session::Entity as Session;
pub use super::session_request::Entity as SessionRequest;
pub use super::user::Entity as User;
pub use super::user_identity::Entity as UserIdentity;
